"testdata": {
    Pet: {
      shape: class
      "id": "string[uuid]"
      "name": "string"
      "store": "string[uuid]"
    }

    Pet Store: {
      shape: class
      "id": "string[uuid]"
      "name": "string"
    }
}

testdata.Pet -- testdata.Pet Store: associates